name: NSLS-II-MIDAS
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda
  - anaconda-client
  - anaconda-navigator
  - anaconda-project
  - pip

  - pip:
    - h5py
    - numpy
    - pandas
    - pyqt5
    - pyqtgraph
    - pystackreg
    - scikit-image
    - scikit-learn
    - scipy
    - tifffile
    - xraylarch==0.9.51
    - pyshortcuts


