name: NSLS-II-MIDAS
channels:
  - defaults
  - conda-forge
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - blosc=1.21.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - cached-property=1.5.2
  - certifi=2021.5.30
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.6.2
  - decorator=5.0.9
  - freetype=2.10.4
  - fsspec=2021.6.0
  - giflib=5.2.1
  - h5py=3.2.1
  - hdf5=1.10.6
  - icc_rt=2019.0.0
  - icu=58.2
  - imagecodecs=2021.6.8
  - imageio=2.9.0
  - intel-openmp=2021.2.0
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=1.0.1
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libdeflate=1.7
  - libpng=1.6.37
  - libtiff=4.2.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - matplotlib-base=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - networkx=2.5
  - numexpr=2.7.3
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - pandas=1.2.5
  - parso=0.7.0
  - partd=1.2.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.3
  - prompt-toolkit=3.0.17
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyqtgraph=0.11.0
  - pyreadline=2.1
  - pystackreg=0.2.5
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.9.7
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - threadpoolctl=2.1.0
  - tifffile=2021.4.8
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.61.2
  - traitlets=5.0.5
  - tzdata=2021a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - asteval==0.9.25
    - atomicwrites==1.4.0
    - attrs==21.2.0
    - chardet==4.0.0
    - fabio==0.11.0
    - future==0.18.2
    - greenlet==1.1.0
    - idna==2.10
    - iniconfig==1.1.1
    - lmfit==1.0.2
    - packaging==21.0
    - peakutils==1.3.3
    - pluggy==0.13.1
    - py==1.10.0
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyshortcuts==1.8.0
    - pytest==6.2.4
    - pywin32==301
    - requests==2.25.1
    - silx==0.15.2
    - sqlalchemy==1.4.20
    - termcolor==1.1.0
    - toml==0.10.2
    - uncertainties==2.4.4
    - urllib3==1.26.6
    - xraydb==4.4.7
    - xraylarch==0.9.51
    - git+git://https://github.com/pattammattel/NSLS-II-MIDAS.git

